### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by tm1000**
Change guzzle to require 6 or 7. Remove throttle library (not used anywhere) and tightenco/collections (also not used anywhere) moved cache/filesystem-adapter to require-dev because nothing requires it but it can be useful for testing

### CODE REVIEW

**Comment by tm1000** [comment]
There is something wrong with the checks as they fail even with guzzle changes which have no effect on your code base (see #3)

**Comment by Skullbock** [comment]
Thanks, gonna release later today

**Comment by Skullbock** [comment]
3.2.0 released

**Comment by tm1000** [comment]
@Skullbock can you push to packagist? https://packagist.org/packages/weble/zohoclient

**Comment by Skullbock** [comment]
Don't why it didn't before... pushed!

**Pull request merged**
