### PR TITLE
Fixes #8

### LINKED ISSUE #8: v4 makes call to Zoho on call to setRefreshToken
I'm noticing that v4 makes a call to Zoho on the initial setRefreshToken before any calls are made to the library. There doesn't seem to be any way around this because `$this->token` is always empty when the class initializes (https://github.com/Weble/ZohoClient/blob/v4/src/OAuthClient.php#L450) (https://github.com/Weble/ZohoClient/blob/v4/src/OAuthClient.php#L464)

In v3 the call to get the access token was not made until `getAccessToken()` was called

We should setRefreshToken blindly here. Don't put it into cache until getAccessToken() is run. Then you can `refreshAccessToken` in `getAccessToken` as well

The overall issue with this is just setting setRefreshToken makes a call out to Zoho even if I never actually reach that code (think of using this in a service provider in Laravel where I have to set the refreshToken in the singleton/bind)

### PR DESCRIPTION
**Pull request by tm1000**
- Fixes #8 
- Stores refreshToken as a string inside of ZohoClient so as to not get reset
- Fixes numerous race conditions (AccessToken not set, refreshToken cleared randomly)
- Adds more tests
- fixes tests to not set a temp directory for cache which can cause tests to output different results on each run
- Use ArrayCachePool with persistent in-memory cache and modify setup so that client is instantiated every run (with persistent cache)
- Also fix cache to be consistent in key names ('_' vs '')
- Add Tests to check cache against array pool
- Fixes and tests getResourceOwner which didn't work because accessToken was set to random uniqid() value in the test
- Removes need to set invalid 'TEMP' accessToken class
- Set region in construct from the region passed in through parameters
- Utilize `Asad\OAuth2\Client\AccessToken\ZohoAccessToken` in place of `League\OAuth2\Client\Token\AccessToken` since we are using `Asad` anyways

Additionally
- Enums Region Class is never used?

Thoughts
- You dont *have* to pass another client to Crm or Books if you dont want to as you can call `getAuthenticatedRequest` against the provider for other libraries. However there might be a benefit in supplying a different client between oauth and crm/books for things like retries.
- Would someone every really call `setAccessToken`? Seems counter-intuitive. Additionally testing this is kind of difficult as we'd need a way to abstract `accessToken`, the call to `getAccessToken()` returns a string (maybe it should return the `accessToken` itself). So at the very least you'd need a `setAccessTokenObjectThing()` to be able to test `setAccessToken`

```
Code Coverage Report:     
  2021-02-05 23:18:16     
                          
 Summary:                 
  Classes:  0.00% (0/2)   
  Methods: 60.00% (18/30) 
  Lines:   56.06% (74/132)

Weble\ZohoClient\Enums\Region
  Methods:  ( 0/ 0)   Lines:  (  0/  0)
Weble\ZohoClient\Exception\AccessDeniedException
  Methods:   0.00% ( 0/ 1)   Lines:   0.00% (  0/  3)
Weble\ZohoClient\Exception\AccessTokenNotSet
  Methods:  ( 0/ 0)   Lines:  (  0/  0)
Weble\ZohoClient\Exception\ApiError
  Methods:  ( 0/ 0)   Lines:  (  0/  0)
Weble\ZohoClient\Exception\CannotGenerateAccessToken
  Methods:  ( 0/ 0)   Lines:  (  0/  0)
Weble\ZohoClient\Exception\CannotGenerateRefreshToken
  Methods:  ( 0/ 0)   Lines:  (  0/  0)
Weble\ZohoClient\Exception\CannotRevokeRefreshToken
  Methods:  ( 0/ 0)   Lines:  (  0/  0)
Weble\ZohoClient\Exception\GrantCodeNotSetException
  Methods:  ( 0/ 0)   Lines:  (  0/  0)
Weble\ZohoClient\Exception\InvalidGrantCodeException
  Methods:  ( 0/ 0)   Lines:  (  0/  0)
Weble\ZohoClient\Exception\RefreshTokenNotSet
  Methods:  ( 0/ 0)   Lines:  (  0/  0)
Weble\ZohoClient\OAuthClient
  Methods:  62.07% (18/29)   Lines:  57.36% ( 74/129)
```

### CODE REVIEW

**Comment by tm1000** [comment]
@Skullbock 👀

**Comment by Skullbock** [comment]
Hi @tm1000 i've not been able to test this yet.
I have a project that uses this, and i'll be updating in this week so i'll probably have some feedback

**Comment by Skullbock** [comment]
Hey @tm1000 i confirm that this works as expected. I think we're ready for a release of a v4. 
If you have any addition / breaking change, now's the time!

**Comment by tm1000** [comment]
@Skullbock I think its fine. Im not using it quite yet (Im still on v3 for my unreleased work) the reasoning is only because I'd have to fork Crm and Books to be able to accept our changes to client

**Comment by Skullbock** [comment]
@tm1000 you can fetch my branch for zoho crm using the `dev-` syntax for composer.
But anyway, i think i'll release this as v4 next week and work on stabilizing the crm library with a v5.

**Comment by tm1000** [comment]
Don't forget about the books library too!

**Comment by Skullbock** [comment]
@tm1000 i release v4 of zoho client, and tagged a v4.5.0 of zoho books that allows for v3 and v4 of the client
This way, along with the crm branch, you should be able to use v4 on the 2 projects

cheers

**Comment by tm1000** [comment]
@Skullbock I think you broke your stable releases by doing that. I'm getting reports from my engineers that books broke between books v4 and the new crm. 

I'm going to investigate in a few minutes to see what the issue is

**Comment by Skullbock** [comment]
Really strange, since the v4 public api is the same.
Maybe it's the usage of `Region` ?

If so, i'll revert with a `4.5.1` and publish a `5.0.0` with just the new dependency

**Comment by tm1000** [comment]
It might be. I haven't had a chance to check yet. This staff member works in Columbia so he's three hours ahead of me. I was going to check the issue and give you some prs to fix it but wanted to let you know if you were still around

**Comment by Skullbock** [comment]
I'll be around for another hour or so.
Let me know, i'll revert / fix if need be in this hour

**Comment by tm1000** [comment]
Actually I believe The reasoning is because we don't have a dependency on the client. So if crm or books has a dependency of 4 or 5 composer will choose 5 and the client constructor is different between old client and new client.

**Comment by Skullbock** [comment]
You can fix that by forcing the require. Anyway, i'll avoid that problem for you and revert with a 4.5.1 and push a 5.0.0 so you can choose

**Comment by Skullbock** [comment]
Pushed `4.5.1` and `5.0.0`

**Comment by tm1000** [comment]
@Skullbock these changes made it into the v4 branch but you merged the develop branch into master not v4. So the published 4.0.0 is actually missing all of the work from this PR and is essentially broken for what I need.

**Comment by Skullbock** [comment]
I don't know what the fuck happened. I think my local git client got fucked up or something. 

Anyway I'll merge this tomorrow morning. 🙏🏻

**Comment by tm1000** [comment]
@Skullbock don't worry. I was just as confused 🙃

**Comment by Skullbock** [comment]
@tm1000 should've release 4.1.0 correctly! let me know if anything still is amiss

**Comment by tm1000** [comment]
@Skullbock you didnt publish to packagist https://packagist.org/packages/weble/zohoclient

Additionally crm and books still link against -dev. I've figured out a way to work around it for now for testing (my CRM tests all passed yay!)

**Comment by tm1000** [comment]
@Skullbock sorry to keep bothering you but I'm stuck again. You see this library isn't published to packagist with a 4.1.0 but that doesnt mater anyways because the crm and books librarys are bound against v4.x-dev of this library and so it's just causing massive headaches for me. Can we just publish all three? or are you waiting for me to test them out?

**Comment by Skullbock** [comment]
Hey @tm1000 this is on pourpose, we were testing it
It seems to work, so we'll probably release later today

**Pull request merged**
